DELETE FROM DetalleOrden;
DELETE FROM Orden;
DELETE FROM Cliente;
DELETE FROM Empleado WHERE jefe IS NOT NULL;
DELETE FROM Empleado;
DELETE FROM PromocionProducto;
DELETE FROM PromocionVigencia;
DELETE FROM Promocion;
DELETE FROM ProveedorCategoria;
DELETE FROM Producto;
DELETE FROM Proveedor;
DELETE FROM Categoria;
DELETE FROM Usuario;
DELETE FROM TipoCliente;

$cat1 = INSERT INTO Categoria (descripcion) VALUES ('Computacion');
$cat2 = INSERT INTO Categoria (descripcion) VALUES ('Telefonia');
$cat3 = INSERT INTO Categoria (descripcion) VALUES ('Videouegos');
$prov1 = INSERT INTO Proveedor (empresa, contacto, direccion) VALUES ('Sony', 'Juan Gonzalez', 'Pje. Della Paolera 22 Piso 15');
$prov2 = INSERT INTO Proveedor (empresa, contacto, direccion) VALUES ('Dell', 'Carlos Graggero', 'Ing. Butty 214 Piso 3');
$prov3 = INSERT INTO Proveedor (empresa, contacto, direccion) VALUES ('Samsung', 'Francisco Heredia', 'Av. Ejercito de Salvacion 311');
$prov4 = INSERT INTO Proveedor (empresa, contacto, direccion) VALUES ('Microsoft', 'Gerardo GarcÃia', 'Bulnes 518 Piso 7');
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES ($prov1, $cat1);
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES ($prov1, $cat2);
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES ($prov1, $cat3);
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES ($prov2, $cat1);
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES ($prov3, $cat1);
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES ($prov3, $cat2);
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES ($prov4, $cat3);
$prod1 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Notebook Vaio SVN1445210', $prov1, $cat1, 1300, 5, 2, 0);
$prod2 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Notebook Vaio SVN1562883', $prov1, $cat1, 980, 2, 3, 0);
$prod3 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Ultrabook Slim Vaio SVUB15551', $prov1, $cat1, 1800, 1, 1, 0);
$prod4 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Inspiron 14-55312', $prov2, $cat1, 540, 6, 0, 0);
$prod5 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Latitude 12-24411', $prov2, $cat1, 1100, 3, 0, 0);
$prod6 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Chromebook 13KBE04', $prov3, $cat1, 880, 1, 3, 0);
$prod7 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Xperia V6', $prov1, $cat2, 660, 3, 1, 0);
$prod8 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Xperia V9', $prov1, $cat2, 1200, 1, 0, 0);
$prod9 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('S8', $prov3, $cat2, 990, 4, 3, 0);
$prod10 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('S8', $prov3, $cat2, 990, 4, 3, 0);
$prod11 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('S8 mini', $prov3, $cat2, 550, 8, 2, 0);
$prod12 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('S9', $prov3, $cat2, 1300, 3, 0, 0);
$prod13 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('S9 mini', $prov3, $cat2, 670, 5, 2, 0);
$prod14 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Playstation 4 500 MB', $prov4, $cat3, 700, 5, 3, 0);
$prod15 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Playstation 4 1000 MG', $prov4, $cat3, 1100, 3, 1, 0);
$prod16 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Mando Playstation XV3432', $prov4, $cat3, 150, 3, 0, 0);
$prod17 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Xbox One', $prov1, $cat3, 1100, 4, 0, 0);
$prod18 = INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Mando Xbox Bateria VBB133123', $prov1, $cat3, 170, 3, 0, 0);
$promo1 = INSERT INTO Promocion (descripcion) VALUES ('Promo Tarjeta Naranja');
$promo2 = INSERT INTO Promocion (descripcion) VALUES ('Promo Banco Galicia');
$promo3 = INSERT INTO Promocion (descripcion) VALUES ('Promo Clarin 365');
$vig1 = INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES ($promo1, NOW - 10, NOW + 5);
$vig2 = INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES ($promo1, NOW - 30, NOW - 20);
$vig3 = INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES ($promo2, NOW - 28, NOW - 20);
$vig4 = INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES ($promo2, NOW - 5, NOW + 2);
$vig5 = INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES ($promo2, NOW - 21, NOW - 16);
$vig6 = INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES ($promo3, NOW - 29, NOW - 11);
$vig7 = INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES ($promo3, NOW - 7, NOW - 2);
$vig8 = INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES ($promo3, NOW + 1, NOW + 7);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod2, $vig1, 0.2);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod5, $vig1, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod8, $vig1, 0.1);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod5, $vig2, 0.1);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod8, $vig2, 0.2);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod5, $vig3, 0.2);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod9, $vig3, 0.4);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod14, $vig3, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod10, $vig4, 0.2);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod9, $vig4, 0.6);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod17, $vig4, 0.2);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod5, $vig5, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod9, $vig5, 0.6);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod10, $vig5, 0.4);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod4, $vig6, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod9, $vig6, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod15, $vig6, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod4, $vig7, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod9, $vig7, 0.5);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod15, $vig7, 0.1);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod18, $vig7, 0.2);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod9, $vig8, 0.5);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod15, $vig8, 0.35);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES ($prod18, $vig8, 0.25);
$usr1 = INSERT INTO Usuario (username, password) VALUES ('mgallardo', '123');
$usr2 = INSERT INTO Usuario (username, password) VALUES ('rvillar', '123');
$usr3 = INSERT INTO Usuario (username, password) VALUES ('mmontana', '123');
$usr4 = INSERT INTO Usuario (username, password) VALUES ('mroldan', '123');
$usr5 = INSERT INTO Usuario (username, password) VALUES ('pperez', '123');
$usr6 = INSERT INTO Usuario (username, password) VALUES ('ematsu', '123');
$usr7 = INSERT INTO Usuario (username, password) VALUES ('aconfort', '123');
$tipo1 = INSERT INTO TipoCliente (descripcion) VALUES ('Consumidor Final');
$tipo2 = INSERT INTO TipoCliente (descripcion) VALUES ('Revendedor');
$cli1 = INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES ($usr1, 'Marcelo Gallardo', 'Pje. Los Robles 351', $tipo1);
$cli2 = INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES ($usr2, 'Ricardo Villar', 'Av. Jose Mari­a Moreno 667', $tipo1);
$cli3 = INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES ($usr3, 'Maria Montana', 'Ramon Falcon 5123', $tipo1);
$cli4 = INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES ($usr4, 'Marcelo Roldan', 'Donato Ãlvarez 145', $tipo1);
$cli5 = INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES ($usr5, 'Paula Perez', 'Av. Del Libertador 7734', $tipo1);
$cli6 = INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES ($usr6, 'Electronica Matsushita', 'Av. Rivadavia 1241', $tipo2);
$cli7 = INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES ($usr7, 'Audio Confort', 'Av. Santa Fe 3411', $tipo2);
$emp1 = INSERT INTO Empleado (nombre) VALUES ('JosÃ© VelÃ¡zquez');
$emp2 = INSERT INTO Empleado (nombre, jefe) VALUES ('Pedro Galimberti', $emp1);
$emp3 = INSERT INTO Empleado (nombre, jefe) VALUES ('Carlos Marti­nez', $emp1);
$emp4 = INSERT INTO Empleado (nombre, jefe) VALUES ('Reynaldo Jauregui', $emp1);
$emp5 = INSERT INTO Empleado (nombre, jefe) VALUES ('Ramon Sinay', $emp4);
$emp6 = INSERT INTO Empleado (nombre, jefe) VALUES ('Pedro Alfonso', $emp4);
$emp7 = INSERT INTO Empleado (nombre, jefe) VALUES ('Ricardo Garcia', $emp3);
$emp8 = INSERT INTO Empleado (nombre, jefe) VALUES ('Maribel Flores', $emp3);
$ord1 = INSERT INTO Orden (cliente, empleado, fechaGenerada) VALUES ($cli1, $emp1, NOW);
$ord2 = INSERT INTO Orden (cliente, empleado, fechaGenerada) VALUES ($cli1, $emp2, NOW);
$ord3 = INSERT INTO Orden (cliente, empleado, fechaGenerada) VALUES ($cli2, $emp3, NOW);
$ord4 = INSERT INTO Orden (cliente, empleado, fechaGenerada) VALUES ($cli2, $emp4, NOW);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES ($ord1, $prod1, 2);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES ($ord1, $prod2, 1);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES ($ord1, $prod3, 3);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES ($ord2, $prod5, 1);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES ($ord3, $prod4, 1);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES ($ord3, $prod1, 2);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES ($ord4, $prod2, 3);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES ($ord4, $prod3, 1);
