DELETE FROM DetalleOrden;
DELETE FROM Orden;
DELETE FROM Cliente;
DELETE FROM Empleado WHERE jefe IS NOT NULL;
DELETE FROM Empleado;
DELETE FROM PromocionProducto;
DELETE FROM PromocionVigencia;
DELETE FROM Promocion;
DELETE FROM ProveedorCategoria;
DELETE FROM Producto;
DELETE FROM Proveedor;
DELETE FROM Categoria;
DELETE FROM Usuario;
DELETE FROM TipoCliente;

INSERT INTO Categoria (descripcion) VALUES ('Computación');
INSERT INTO Categoria (descripcion) VALUES ('Telefonía');
INSERT INTO Categoria (descripcion) VALUES ('Videouegos');
INSERT INTO Proveedor (empresa, contacto, direccion) VALUES ('Sony', 'Juan González', 'Pje. Della Paolera 22 Piso 15');
INSERT INTO Proveedor (empresa, contacto, direccion) VALUES ('Dell', 'Carlos Graggero', 'Ing. Butty 214 Piso 3');
INSERT INTO Proveedor (empresa, contacto, direccion) VALUES ('Samsung', 'Francisco Heredia', 'Av. Ejército de Salvación 311');
INSERT INTO Proveedor (empresa, contacto, direccion) VALUES ('Microsoft', 'Gerardo García', 'Bulnes 518 Piso 7');
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES (1, 1);
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES (1, 2);
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES (1, 3);
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES (2, 1);
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES (3, 1);
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES (3, 2);
INSERT INTO ProveedorCategoria (proveedor, categoria) VALUES (4, 3);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Notebook Vaio SVN1445210', 1, 1, 1300, 5, 2, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Notebook Vaio SVN1562883', 1, 1, 980, 2, 3, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Ultrabook Slim Vaio SVUB15551', 1, 1, 1800, 1, 1, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Inspiron 14-55312', 2, 1, 540, 6, 0, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Latitude 12-24411', 2, 1, 1100, 3, 0, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Chromebook 13KBE04', 3, 1, 880, 1, 3, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Xperia V6', 1, 2, 660, 3, 1, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Xperia V9', 1, 2, 1200, 1, 0, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('S8', 3, 2, 990, 4, 3, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('S8', 3, 2, 990, 4, 3, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('S8 mini', 3, 2, 550, 8, 2, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('S9', 3, 2, 1300, 3, 0, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('S9 mini', 3, 2, 670, 5, 2, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Playstation 4 500 MB', 4, 3, 700, 5, 3, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Playstation 4 1000 MG', 4, 3, 1100, 3, 1, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Mando Playstation XV3432', 4, 3, 150, 3, 0, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Xbox One', 1, 3, 1100, 4, 0, 0);
INSERT INTO Producto (descripcion, proveedor, categoria, precioUnitario, unidadesStock, unidadesReposicion, flgDiscontinuo) VALUES ('Mando Xbox Bateria VBB133123', 1, 3, 170, 3, 0, 0);
INSERT INTO Promocion (descripcion) VALUES ('Promo Tarjeta Naranja');
INSERT INTO Promocion (descripcion) VALUES ('Promo Banco Galicia');
INSERT INTO Promocion (descripcion) VALUES ('Promo Clarin 365');
INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES (1, '2026-09-24', '2026-10-01');
INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES (1, '2026-09-09', '2026-09-14');
INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES (1, '2026-08-30', '2026-08-25');
INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES (2, '2026-09-22', '2026-09-29');
INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES (2, '2026-09-06', '2026-09-11');
INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES (3, '2026-08-29', '2026-09-16');
INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES (3, '2026-09-20', '2026-09-25');
INSERT INTO PromocionVigencia (promocion, fechaInicio, fechaFin) VALUES (3, '2026-09-28', '2026-10-04');
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (2, 1, 0.2);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (5, 1, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (8, 1, 0.1);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (5, 2, 0.1);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (8, 2, 0.2);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (5, 3, 0.2);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (9, 3, 0.4);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (14, 3, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (10, 4, 0.2);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (9, 4, 0.6);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (17, 4, 0.2);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (5, 5, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (9, 5, 0.6);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (10, 5, 0.4);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (4, 6, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (9, 6, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (15, 6, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (4, 7, 0.3);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (9, 7, 0.5);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (15, 7, 0.1);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (18, 7, 0.2);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (9, 8, 0.5);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (15, 8, 0.35);
INSERT INTO PromocionProducto (producto, promocionVigencia, descuento) VALUES (18, 8, 0.25);
INSERT INTO Usuario (username, password) VALUES ('mgallardo', '123');
INSERT INTO Usuario (username, password) VALUES ('rvillar', '123');
INSERT INTO Usuario (username, password) VALUES ('mmontana', '123');
INSERT INTO Usuario (username, password) VALUES ('mroldan', '123');
INSERT INTO Usuario (username, password) VALUES ('pperez', '123');
INSERT INTO Usuario (username, password) VALUES ('ematsu', '123');
INSERT INTO Usuario (username, password) VALUES ('aconfort', '123');
INSERT INTO TipoCliente (descripcion) VALUES ('Consumidor Final');
INSERT INTO TipoCliente (descripcion) VALUES ('Revendedor');
INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES (1, 'Marcelo Gallardo', 'Pje. Los Robles 351', 1);
INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES (2, 'Ricardo Villar', 'Av. José María Moreno 667', 1);
INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES (3, 'María Montana', 'Ramón Falcón 5123', 1);
INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES (4, 'Marcelo Roldán', 'Donato Álvarez 145', 1);
INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES (5, 'Paula Pérez', 'Av. Del Libertador 7734', 1);
INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES (6, 'Electrónica Matsushita', 'Av. Rivadavia 1241', 2);
INSERT INTO Cliente (usuario, nombre, direccion, tipoCliente) VALUES (7, 'Audio Confort', 'Av. Santa Fe 3411', 2);
INSERT INTO Empleado (nombre) VALUES ('José Velázquez');
INSERT INTO Empleado (nombre, jefe) VALUES ('Pedro Galimberti', 1);
INSERT INTO Empleado (nombre, jefe) VALUES ('Carlos Martínez', 1);
INSERT INTO Empleado (nombre, jefe) VALUES ('Reynaldo Jauregui', 1);
INSERT INTO Empleado (nombre, jefe) VALUES ('Ramón Sinay', 4);
INSERT INTO Empleado (nombre, jefe) VALUES ('Pedro Alfonso', 4);
INSERT INTO Empleado (nombre, jefe) VALUES ('Ricardo García', 3);
INSERT INTO Empleado (nombre, jefe) VALUES ('Maribel Flores', 3);
INSERT INTO Orden (cliente, empleado, fechaGenerada) VALUES (1, 1, NOW);
INSERT INTO Orden (cliente, empleado, fechaGenerada) VALUES (1, 2, NOW);
INSERT INTO Orden (cliente, empleado, fechaGenerada) VALUES (2, 3, NOW);
INSERT INTO Orden (cliente, empleado, fechaGenerada) VALUES (2, 4, NOW);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES (1, 1, 2);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES (1, 2, 1);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES (1, 3, 3);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES (2, 5, 1);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES (3, 4, 1);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES (3, 1, 2);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES (4, 2, 3);
INSERT INTO DetalleOrden (orden, producto, cantidad) VALUES (4, 3, 1);
